### PR TITLE
chore: remove mistakenly added symbol

### PR DESCRIPTION
**Pull request by anton-dzhanaev**
I assume this symbol should not be there :)

### CODE REVIEW

**Comment by anton-dzhanaev** [comment]
@cla-bot check

**Comment by anton-dzhanaev** [comment]
@cla-bot check

**Comment by anton-dzhanaev** [comment]
@cla-bot check

**Comment by lini** [comment]
Hi there, I am going to merge this now, but for future reference - in order to properly sign the CLA, make sure you supply the same Github username and email address in the form as the ones you used when you made the commit and pull request.

**Pull request closed without merging**
